---
# Options
__galaxy_profile: 'standalone'
__galaxy_dev_source_path: 'pulpcore:pulp_ansible:pulp_container:galaxy_ng:galaxy-importer'
__galaxy_lock_requirements: '0'

pulp_git_url: https://github.com/pulp/pulpcore.git
pulp_git_revision: "3.14.4"
pulpcore_version: 3.14.4
pulp_devel_supplement_bashrc: true
pulp_default_admin_password: password
pulp_webserver_disable_https: true
pulp_user: "vagrant"
developer_user: "vagrant"
developer_user_home: "/home/vagrant"
pulp_workers: 4
pulp_api_workers: 4
pulp_settings:
  secret_key: "unsafe_default"
  content_origin: "http://{{ ansible_fqdn }}"
  x_pulp_api_host: 127.0.0.1
  x_pulp_api_port: 24817
  x_pulp_api_user: "admin"
  x_pulp_api_password: "{{ pulp_default_admin_password }}"
  x_pulp_api_prefix: "pulp_ansible/galaxy/automation-hub/api"
  galaxy_require_content_approval: "False"
  pulp_token_auth_disabled: "True"
  galaxy_api_default_distribution_base_path: "published"

pulp_devel_supplement_bashrc: true
pulp_default_admin_password: password
pulp_install_plugins:
  #galaxy-ng:
  #   source_dir: "/home/vagrant/devel/galaxy_ng"
  # pulp-2to3-migration:
  #   source_dir: "/home/vagrant/devel/pulp-2to3-migration"
  pulp-ansible:
     source_dir: "/home/vagrant/devel/pulp_ansible"
     # git_url: "https://github.com/pulp/pulp_ansible"  # optional git repo
     # git_revision: "0.7.3"  # optional specific branch/tag/commit
  # pulp-certguard:
  #   source_dir: "/home/vagrant/devel/pulp-certguard"
  #pulp-container:
  #   source_dir: "/home/vagrant/devel/pulp_container"
